### ISSUE TITLE
Week 2 feedback

### ISSUE THREAD

**Issue by rarmatei** [MHDRateb/Homwork-1-#2]
Nicely done! The website works as expected, everything is arranged like in the sketch and the media queries fire when you resize the page.

Two things for now:

Can you please try and use indentation in yours css? In VS Code you just highlight a bit of text and press TAB to indent it.

```css
//without indentation
ul.topnav li a {
display: block;
color: white;
padding: 8px 30px;
text-decoration: none;
}
//with indendation
ul.topnav li a {
  display: block;
  color: white;
  padding: 8px 30px;
  text-decoration: none;
}
```

Your images have spaces in their file names. Some environments may throw an error when they see the space, and it's generally preferred to avoid any space in any file names. You can use an underscore `_` instead of the space.
